FROM node:15.0-alpine AS builder

WORKDIR /usr/src/frontend
COPY package.json yarn.lock ./
RUN yarn install --ignore-engines
RUN yarn

ENV PATH="./node_modules/.bin:$PATH"

COPY . ./
RUN yarn run env-cmd -f env.prod react-scripts build

FROM nginx:1.17-alpine
RUN apk --no-cache add curl
RUN curl -L https://github.com/a8m/envsubst/releases/download/v1.1.0/envsubst-`uname -s`-`uname -m` -o envsubst && \
    chmod +x envsubst && \
    mv envsubst /usr/local/bin
COPY ./nginx.config /etc/nginx/nginx.template
CMD ["/bin/sh", "-c", "envsubst < /etc/nginx/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
COPY --from=builder /usr/src/frontend/build /usr/share/nginx/html