version: '3.9'
services:
  frontend:
    build:
      context: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/frontend
  backend:
    build:
      context: backend
    volumes:
      - ./backend:/usr/src/backend
    ports:
      - "8000:8000"
