# Generated by Django 3.2.7 on 2021-09-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_name', models.CharField(choices=[('Flare Wallet', 'Flare Wallet'), ('Atomic Wallet', 'Atomic Wallet'), ('Coinomi', 'Coinomi'), ('MetaMask', 'MetaMask'), ('TrustWallet', 'TrustWallet'), ('WalletConnect', 'WalletConnect'), ('Coinbase Wallet', 'Coinbase Wallet'), ('Ledger', 'Ledger'), ('Trezor', 'Trezor'), ('Formatic', 'Formatic'), ('Portis', 'Portis'), ('Squarelink', 'Squarelink'), ('Torus', 'Torus'), ('Authereum', 'Authereum'), ('VeChain', 'VeChain'), ('Scatter Wallet', 'Scatter Wallet'), ('Math Wallet', 'Math Wallet'), ('BlockChain', 'BlockChain'), ('Binance Smart Chain', 'Binance Smart Chain'), ('Guada Wallet', 'Guada Wallet'), ('Exodus', 'Exodus')], max_length=50)),
            ],
        ),
    ]
