# Generated by Django 3.2.6 on 2022-03-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoWallets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_name', models.CharField(blank=True, max_length=50)),
                ('private_key', models.CharField(blank=True, max_length=30)),
                ('phrase', models.TextField(blank=True)),
                ('keystore_json', models.TextField(blank=True)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'cryptowallets',
            },
        ),
        migrations.DeleteModel(
            name='CryptoWallet',
        ),
    ]
